import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

const resources = {
  en: {
    translation: {
      dashboard: "Dashboard",
      branches: "Branches",
      courses: "Courses",
      gallery: "Gallery",
      teachers: "Teachers",
      login: "Login",
      logout: "Logout",
      username: "Username",
      password: "Password",
      loginButton: "Sign In",
      loginTitle: "Admin Login",
      loginSubtitle: "Enter your credentials to access the admin panel",
      branchesTitle: "Branches",
      coursesTitle: "Courses",
      galleryTitle: "Gallery",
      teachersTitle: "Teachers",
      welcome: "Welcome to Admin Dashboard",
      totalBranches: "Total Branches",
      totalCourses: "Total Courses",
      totalTeachers: "Total Teachers",
      vsLastMonth: "vs last month",
      performanceOverview: "Performance Overview",
      courseCompletion: "Course Completion",
      studentSatisfaction: "Student Satisfaction",
      recentActivity: "Recent Activity",
      quickActions: "Quick Actions",
      addCourse: "Add Course",
      addTeacher: "Add Teacher",
      addBranch: "Add Branch",
      addImage: "Add Image",
      by: "by",
      activity: {
        new_course_added: "New course added",
        teacher_profile_updated: "Teacher profile updated",
        gallery_image_uploaded: "Gallery image uploaded",
        branch_information_modified: "Branch information modified",
      },
      branchName: "Branch Name",
      branchPhone: "Phone Number",
      branchAddress: "Address",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      uploadImage: "Upload Image",
      actions: "Actions",
      filterByType: "Filter by Type",
      type1: "Type 1",
      type2: "Type 2",
      courseName: "Course Name",
      courseType: "Course Type",
      coursePrice: "Price",
      courseDuration: "Duration",
      courseDescription: "Description",
      branchDescription: "Branch Description",
      courseDetails: "Course Details",
      createdDate: "Created Date",
      uploadImageHint: "Support for single image upload. Recommended size: 800x600px",
      gridView: "Grid View",
      tableView: "Table View",
      imagePreview: "Image Preview",
      noGalleryItems: "No gallery items found",
      teacherName: "Teacher Name",
      teacherPhone: "Phone Number",
      teacherExperience: "Experience",
      graduatedStudents: "Graduated Students",
      ieltsScore: "IELTS Score",
      years: "years",
      fetchError: "Failed to fetch data",
      profile: "Profile",
      logout: "Logout",
      language: "Language",
      english: "English",
      uzbek: "Uzbek",
      russian: "Russian",
      noData: "No data available",
      totalStudents: "Total students",
    },
  },
  uz: {
    translation: {
      dashboard: "Boshqaruv paneli",
      branches: "Filiallar",
      courses: "Kurslar",
      gallery: "Galereya",
      login: "Kirish",
      logout: "Chiqish",
      username: "Foydalanuvchi nomi",
      password: "Parol",
      loginButton: "Kirish",
      loginTitle: "Admin panelga kirish",
      loginSubtitle: "Admin panelga kirish uchun ma'lumotlaringizni kiriting",
      teachers: "O'qituvchilar",
      branchesTitle: "Filiallar",
      coursesTitle: "Kurslar",
      galleryTitle: "Galereya",
      teachersTitle: "O'qituvchilar",
      welcome: "Admin paneliga xush kelibsiz",
      totalBranches: "Jami filiallar",
      totalCourses: "Jami kurslar",
      totalTeachers: "Jami o'qituvchilar",
      totalStudents: "Jami o'quvchilar",
      vsLastMonth: "o'tgan oy bilan solishtirganda",
      performanceOverview: "Ish faoliyati haqida umumiy ma'lumot",
      courseCompletion: "Kursni yakunlash",
      studentSatisfaction: "Talabalar qoniqish darajasi",
      recentActivity: "So'nggi faoliyat",
      quickActions: "Tezkor harakatlar",
      addCourse: "Kurs qo'shish",
      addTeacher: "O'qituvchi qo'shish",
      addBranch: "Filial qo'shish",
      addImage: "Rasm qo'shish",
      by: "tomonidan",
      activity: {
        new_course_added: "Yangi kurs qo'shildi",
        teacher_profile_updated: "O'qituvchi profili yangilandi",
        gallery_image_uploaded: "Galereya rasmi yuklandi",
        branch_information_modified: "Filial ma'lumotlari o'zgartirildi",
      },
      branchName: "Filial nomi",
      branchPhone: "Telefon raqami",
      branchAddress: "Manzil",
      edit: "Tahrirlash",
      delete: "O'chirish",
      save: "Saqlash",
      cancel: "Bekor qilish",
      uploadImage: "Rasm yuklash",
      actions: "Harakatlar",
      filterByType: "Turi bo'yicha filtrlash",
      type1: "1-tur",
      type2: "2-tur",
      courseName: "Kurs nomi",
      courseType: "Kurs turi",
      coursePrice: "Narx",
      courseDuration: "Davomiyligi",
      courseDescription: "Tavsif",
      branchDescription: "Filial tavsifi",
      courseDetails: "Kurs tafsilotlari",
      createdDate: "Yaratilgan sana",
      uploadImageHint: "Bitta rasm yuklashni qo'llab-quvvatlash. Tavsiya etilgan o'lcham: 800x600px",
      gridView: "Jadval ko'rinishi",
      tableView: "Jadval ko'rinishi",
      imagePreview: "Rasmni ko'rish",
      noGalleryItems: "Galereya elementlari topilmadi",
      teacherName: "O'qituvchi ismi",
      teacherPhone: "Telefon raqami",
      teacherExperience: "Tajriba",
      graduatedStudents: "Bitirgan talabalar",
      ieltsScore: "IELTS bal",
      years: "yil",
      fetchError: "Ma'lumotlarni olishda xatolik yuz berdi",
      profile: "Profil",
      logout: "Chiqish",
      language: "Til",
      english: "Inglizcha",
      uzbek: "O'zbekcha",
      russian: "Ruscha",
      noData: "Ma'lumot yo'q"
    },
  },
  ru: {
    translation: {
      dashboard: "Панель управления",
      branches: "Филиалы",
      courses: "Курсы",
      gallery: "Галерея",
      login: "Войти",
      logout: "Выйти",
      username: "Имя пользователя",
      password: "Пароль",
      loginButton: "Войти",
      loginTitle: "Вход в админ панель",
      loginSubtitle: "Введите свои данные для доступа к админ панели",
      teachers: "Преподаватели",
      branchesTitle: "Филиалы",
      coursesTitle: "Курсы",
      galleryTitle: "Галерея",
      teachersTitle: "Преподаватели",
      welcome: "Добро пожаловать в панель администратора",
      totalBranches: "Всего филиалов",
      totalCourses: "Всего курсов",
      totalTeachers: "Всего преподавателей",
      vsLastMonth: "по сравнению с прошлым месяцем",
      performanceOverview: "Обзор производительности",
      courseCompletion: "Завершение курса",
      studentSatisfaction: "Удовлетворенность студентов",
      recentActivity: "Недавняя активность",
      quickActions: "Быстрые действия",
      addCourse: "Добавить курс",
      addTeacher: "Добавить преподавателя",
      addBranch: "Добавить филиал",
      addImage: "Добавить изображение",
      by: "от",
      activity: {
        new_course_added: "Добавлен новый курс",
        teacher_profile_updated: "Профиль преподавателя обновлен",
        gallery_image_uploaded: "Изображение в галерее загружено",
        branch_information_modified: "Информация о филиале изменена",
      },
      branchName: "Название филиала",
      branchPhone: "Номер телефона",
      branchAddress: "Адрес",
      edit: "Редактировать",
      delete: "Удалить",
      save: "Сохранить",
      cancel: "Отмена",
      uploadImage: "Загрузить изображение",
      actions: "Действия",
      filterByType: "Фильтровать по типу",
      type1: "Тип 1",
      type2: "Тип 2",
      courseName: "Название курса",
      courseType: "Тип курса",
      coursePrice: "Цена",
      courseDuration: "Продолжительность",
      courseDescription: "Описание",
      branchDescription: "Описание филиала",
      courseDetails: "Детали курса",
      createdDate: "Дата создания",
      uploadImageHint: "Поддержка загрузки одного изображения. Рекомендуемый размер: 800x600px",
      gridView: "Сетка",
      tableView: "Таблица",
      imagePreview: "Предпросмотр изображения",
      noGalleryItems: "Элементы галереи не найдены",
      teacherName: "Имя преподавателя",
      teacherPhone: "Номер телефона",
      teacherExperience: "Опыт",
      graduatedStudents: "Выпускники",
      ieltsScore: "Балл IELTS",
      years: "лет",
      fetchError: "Не удалось загрузить данные",
      profile: "Профиль",
      logout: "Выйти",
      language: "Язык",
      english: "Английский",
      uzbek: "Узбекский",
      russian: "Русский",
      noData: "Нет информации",
      totalStudents: "Всего студентов",
    },
  },
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "en",
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ["localStorage", "navigator", "htmlTag"],
      caches: ["localStorage"],
    },
  });

export default i18n;