import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";
const resources = {
  en: {
    translation: {
      // Existing translations from previous components...
      dashboard: "Dashboard",
      branches: "Branches",
      courses: "Courses",
      gallery: "Gallery",
      teachers: "Teachers",
      login: "Login",
      logout: "Logout",
      username: "Username",
      password: "Password",
      loginButton: "Sign In",
      loginTitle: "Admin Login",
      loginSubtitle: "Enter your credentials to access the admin panel",
      branchesTitle: "Branches",
      coursesTitle: "Courses",
      galleryTitle: "Gallery",
      teachersTitle: "Teachers",
      welcome: "Welcome to Admin Dashboard",
      totalBranches: "Total Branches",
      totalCourses: "Total Courses",
      totalTeachers: "Total Teachers",
      vsLastMonth: "vs last month",
      performanceOverview: "Performance Overview",
      courseCompletion: "Course Completion",
      studentSatisfaction: "Student Satisfaction",
      recentActivity: "Recent Activity",
      quickActions: "Quick Actions",
      addCourse: "Add Course",
      addTeacher: "Add Teacher",
      addBranch: "Add Branch",
      addImage: "Add Image",
      by: "by",
      activity: {
        new_course_added: "New course added",
        teacher_profile_updated: "Teacher profile updated",
        gallery_image_uploaded: "Gallery image uploaded",
        branch_information_modified: "Branch information modified",
      },
      branchName: "Branch Name",
      branchPhone: "Phone Number",
      branchAddress: "Address",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      uploadImage: "Upload Image",
      actions: "Actions",
      filterByType: "Filter by Type",
      type1: "Type 1",
      type2: "Type 2",
      courseName: "Course Name",
      courseType: "Course Type",
      coursePrice: "Price",
      courseDuration: "Duration",
      courseDescription: "Description",
      branchDescription: "Branch Description",
      courseDetails: "Course Details",
      createdDate: "Created Date",
      uploadImageHint: "Support for single image upload. Recommended size: 800x600px",
      gridView: "Grid View",
      tableView: "Table View",
      imagePreview: "Image Preview",
      noGalleryItems: "No gallery items found",
      teacherName: "Teacher Name",
      teacherPhone: "Phone Number",
      teacherExperience: "Experience",
      graduatedStudents: "Graduated Students",
      ieltsScore: "IELTS Score",
      years: "years",
      fetchError: "Failed to fetch data",
      profile: "Profile",
      logout: "Logout",
      language: "Language",
      english: "English",
      uzbek: "Uzbek",
      russian: "Russian",
      noData: "No data available",
      totalStudents: "Total students",
      courseApplications: "All requests",
      branchHeader: "Branches",
      branchSubtitle: "Manage all branches",
      addBranchButton: "Add Branch",
      editBranch: "Edit Branch",
      deleteBranch: "Delete Branch",
      deleteConfirm: "Are you sure you want to delete this branch?",
      okText: "Yes",
      cancelText: "No",
      branchNameUz: "Branch Name (Uzbek)",
      branchNameEn: "Branch Name (English)",
      branchNameRu: "Branch Name (Russian)",
      contactLabel: "Phone Number",
      googleUrl: "Google Maps URL",
      yandexUrl: "Yandex Maps URL",
      uploadImageLabel: "Upload Image",
      removeImage: "Remove Image",
      existingImageUrl: "Existing Image URL",
      nameUzRequired: "Branch name (Uzbek) is required",
      nameEnRequired: "Branch name (English) is required",
      nameRuRequired: "Branch name (Russian) is required",
      contactRequired: "Phone number is required",
      googleUrlRequired: "Google Maps URL is required",
      yandexUrlRequired: "Yandex Maps URL is required",
      imageRequired: "Image upload is required",
      imageSizeError: "Image size must be less than 5MB",
      imageTypeError: "Only image files are allowed",
      uploadSuccess: "Image uploaded successfully",
      uploadError: "Failed to upload image",
      saveSuccess: "Branch saved successfully",
      saveError: "Failed to save branch",
      deleteSuccess: "Branch deleted successfully",
      deleteError: "Failed to delete branch",
      noBranches: "No branches found",
      paginationTotal: "{range0}-{range1} of {total} Branches",
      studentsHeader: "Students",
      addStudentButton: "Add Student",
      editStudent: "Edit Student",
      deleteStudent: "Delete Student",
      deleteStudentConfirm: "Are you sure you want to delete this student?",
      totalStudentsLabel: "Total Students",
      studentName: "Student",
      cefrLevel: "CEFR Level",
      certificate: "Certificate",
      viewCertificate: "View",
      noCertificate: "Not Available",
      nameUzLabel: "Name (Uzbek)",
      nameEnLabel: "Name (English)",
      nameRuLabel: "Name (Russian)",
      cefrLevelLabel: "CEFR Level",
      ieltsScoreLabel: "IELTS Score",
      certificateUploadLabel: "Upload Certificate Image",
      nameUzRequired: "Name (Uzbek) is required",
      nameEnRequired: "Name (English) is required",
      nameRuRequired: "Name (Russian) is required",
      cefrLevelRequired: "CEFR Level is required",
      ieltsScoreRequired: "IELTS Score is required",
      certificateRequired: "Certificate image upload is required",
      certificateUrlLabel: "Existing Certificate URL",
      saveStudentSuccess: "Student saved successfully",
      saveStudentError: "Failed to save student",
      deleteStudentSuccess: "Student deleted successfully",
      deleteStudentError: "Failed to delete student",
      noStudents: "No students found",
      // New translations for Teachers component
      teachersHeader: "Teachers",
      teachersSubtitle: "Manage all teachers",
      addTeacherButton: "Add Teacher",
      editTeacher: "Edit Teacher",
      deleteTeacher: "Delete Teacher",
      deleteTeacherConfirm: "Are you sure you want to delete this teacher?",
      teacherNameLabel: "Teacher",
      experienceYears: "Experience",
      graduatedStudentsLabel: "Graduated Students",
      contactLabel: "Phone Number",
      profilePictureLabel: "Upload Profile Picture",
      profilePictureUrlLabel: "Existing Profile Picture URL",
      nameUzRequired: "Name (Uzbek) is required",
      nameEnRequired: "Name (English) is required",
      nameRuRequired: "Name (Russian) is required",
      contactRequired: "Phone number is required",
      experienceYearsRequired: "Experience years is required",
      graduatedStudentsRequired: "Number of graduated students is required",
      ieltsScoreRequired: "IELTS Score is required",
      profilePictureRequired: "Profile picture upload is required",
      saveTeacherSuccess: "Teacher saved successfully",
      saveTeacherError: "Failed to save teacher",
      deleteTeacherSuccess: "Teacher deleted successfully",
      deleteTeacherError: "Failed to delete teacher",
      noTeachers: "No teachers found",
      paginationTeachersTotal: "{range0}-{range1} of {total} Teachers",
    },
  },
  uz: {
    translation: {
      // Existing translations...
      dashboard: "Boshqaruv paneli",
      branches: "Filiallar",
      courses: "Kurslar",
      gallery: "Galereya",
      login: "Kirish",
      logout: "Chiqish",
      username: "Foydalanuvchi nomi",
      password: "Parol",
      loginButton: "Kirish",
      loginTitle: "Admin panelga kirish",
      loginSubtitle: "Admin panelga kirish uchun ma'lumotlaringizni kiriting",
      teachers: "O'qituvchilar",
      branchesTitle: "Filiallar",
      coursesTitle: "Kurslar",
      galleryTitle: "Galereya",
      teachersTitle: "O'qituvchilar",
      welcome: "Admin paneliga xush kelibsiz",
      totalBranches: "Jami filiallar",
      totalCourses: "Jami kurslar",
      totalTeachers: "Jami o'qituvchilar",
      totalStudents: "Jami o'quvchilar",
      vsLastMonth: "o'tgan oy bilan solishtirganda",
      performanceOverview: "Ish faoliyati haqida umumiy ma'lumot",
      courseCompletion: "Kursni yakunlash",
      studentSatisfaction: "Talabalar qoniqish darajasi",
      recentActivity: "So'nggi faoliyat",
      quickActions: "Tezkor harakatlar",
      addCourse: "Kurs qo'shish",
      addTeacher: "O'qituvchi qo'shish",
      addBranch: "Filial qo'shish",
      addImage: "Rasm qo'shish",
      by: "tomonidan",
      activity: {
        new_course_added: "Yangi kurs qo'shildi",
        teacher_profile_updated: "O'qituvchi profili yangilandi",
        gallery_image_uploaded: "Galereya rasmi yuklandi",
        branch_information_modified: "Filial ma'lumotlari o'zgartirildi",
      },
      branchName: "Filial nomi",
      branchPhone: "Telefon raqami",
      branchAddress: "Manzil",
      edit: "Tahrirlash",
      delete: "O'chirish",
      save: "Saqlash",
      cancel: "Bekor qilish",
      uploadImage: "Rasm yuklash",
      actions: "Harakatlar",
      filterByType: "Turi bo'yicha filtrlash",
      type1: "1-tur",
      type2: "2-tur",
      courseName: "Kurs nomi",
      courseType: "Kurs turi",
      coursePrice: "Narx",
      courseDuration: "Davomiyligi",
      courseDescription: "Tavsif",
      branchDescription: "Filial tavsifi",
      courseDetails: "Kurs tafsilotlari",
      createdDate: "Yaratilgan sana",
      uploadImageHint: "Bitta rasm yuklashni qo'llab-quvvatlash. Tavsiya etilgan o'lcham: 800x600px",
      gridView: "Jadval ko'rinishi",
      tableView: "Jadval ko'rinishi",
      imagePreview: "Rasmni ko'rish",
      noGalleryItems: "Galereya elementlari topilmadi",
      teacherName: "O'qituvchi ismi",
      teacherPhone: "Telefon raqami",
      teacherExperience: "Tajriba",
      graduatedStudents: "Bitirgan talabalar",
      ieltsScore: "IELTS bal",
      years: "yil",
      fetchError: "Ma'lumotlarni olishda xatolik yuz berdi",
      profile: "Profil",
      logout: "Chiqish",
      language: "Til",
      english: "Inglizcha",
      uzbek: "O'zbekcha",
      russian: "Ruscha",
      noData: "Ma'lumot yo'q",
      courseApplications: "Barcha so'rovlar",
      branchHeader: "Filiallar",
      branchSubtitle: "Barcha filiallarni boshqaring",
      addBranchButton: "Filial qo'shish",
      editBranch: "Filialni tahrirlash",
      deleteBranch: "Filialni o'chirish",
      deleteConfirm: "Haqiqatan ham bu filialni o'chirmoqchimisiz?",
      okText: "Ha",
      cancelText: "Yo'q",
      branchNameUz: "Filial nomi (O'zbek)",
      branchNameEn: "Filial nomi (Ingliz)",
      branchNameRu: "Filial nomi (Rus)",
      contactLabel: "Telefon raqami",
      googleUrl: "Google Maps URL",
      yandexUrl: "Yandex Maps URL",
      uploadImageLabel: "Rasm yuklash",
      removeImage: "Rasmni olib tashlash",
      existingImageUrl: "Mavjud rasm URL",
      nameUzRequired: "Filial nomi (O'zbek) zarur",
      nameEnRequired: "Filial nomi (Ingliz) zarur",
      nameRuRequired: "Filial nomi (Rus) zarur",
      contactRequired: "Telefon raqami zarur",
      googleUrlRequired: "Google Maps URL zarur",
      yandexUrlRequired: "Yandex Maps URL zarur",
      imageRequired: "Rasm yuklash zarur",
      imageSizeError: "Rasm hajmi 5MB dan kichik bo'lishi kerak",
      imageTypeError: "Faqat rasm fayllari yuklanadi",
      uploadSuccess: "Rasm muvaffaqiyatli yuklandi",
      uploadError: "Rasm yuklashda xatolik yuz berdi",
      saveSuccess: "Filial muvaffaqiyatli saqlandi",
      saveError: "Filialni saqlashda xatolik yuz berdi",
      deleteSuccess: "Filial muvaffaqiyatli o'chirildi",
      deleteError: "Filialni o'chirishda xatolik yuz berdi",
      noBranches: "Filiallar topilmadi",
      paginationTotal: "{range0}-{range1} / {total} Filiallar",
      studentsHeader: "O'quvchilar",
      addStudentButton: "O'quvchi qo'shish",
      editStudent: "O'quvchini tahrirlash",
      deleteStudent: "O'quvchini o'chirish",
      deleteStudentConfirm: "Haqiqatan ham bu o'quvchini o'chirmoqchimisiz?",
      totalStudentsLabel: "Jami o'quvchilar",
      studentName: "O'quvchi",
      cefrLevel: "CEFR daraja",
      certificate: "Sertifikat",
      viewCertificate: "Ko'rish",
      noCertificate: "Mavjud emas",
      nameUzLabel: "Ism (O'zbekcha)",
      nameEnLabel: "Ism (Inglizcha)",
      nameRuLabel: "Ism (Ruscha)",
      cefrLevelLabel: "CEFR daraja",
      ieltsScoreLabel: "IELTS bal",
      certificateUploadLabel: "Sertifikat rasmni yuklash",
      nameUzRequired: "Ism (O'zbekcha) kiritish majburiy",
      nameEnRequired: "Ism (Inglizcha) kiritish majburiy",
      nameRuRequired: "Ism (Ruscha) kiritish majburiy",
      cefrLevelRequired: "CEFR daraja kiritish majburiy",
      ieltsScoreRequired: "IELTS bal kiritish majburiy",
      certificateRequired: "Sertifikat rasmni yuklash zarur",
      certificateUrlLabel: "Mavjud sertifikat URL",
      saveStudentSuccess: "O'quvchi muvaffaqiyatli saqlandi",
      saveStudentError: "O'quvchini saqlashda xatolik yuz berdi",
      deleteStudentSuccess: "O'quvchi muvaffaqiyatli o'chirildi",
      deleteStudentError: "O'quvchini o'chirishda xatolik yuz berdi",
      noStudents: "O'quvchilar topilmadi",
      // New translations for Teachers component
      teachersHeader: "O'qituvchilar",
      teachersSubtitle: "Barcha o'qituvchilarni boshqaring",
      addTeacherButton: "O'qituvchi qo'shish",
      editTeacher: "O'qituvchini tahrirlash",
      deleteTeacher: "O'qituvchini o'chirish",
      deleteTeacherConfirm: "Haqiqatan ham bu o'qituvchini o'chirmoqchimisiz?",
      teacherNameLabel: "O'qituvchi",
      experienceYears: "Tajriba",
      graduatedStudentsLabel: "Bitirgan o'quvchilar",
      contactLabel: "Telefon raqam",
      profilePictureLabel: "Profil rasmni yuklash",
      profilePictureUrlLabel: "Mavjud rasm URL",
      nameUzRequired: "Ism (O'zbekcha) kiritish majburiy",
      nameEnRequired: "Ism (Inglizcha) kiritish majburiy",
      nameRuRequired: "Ism (Ruscha) kiritish majburiy",
      contactRequired: "Telefon raqam kiritish majburiy",
      experienceYearsRequired: "Tajriba kiritish majburiy",
      graduatedStudentsRequired: "Bitirgan o'quvchilar soni kiritish majburiy",
      ieltsScoreRequired: "IELTS bal kiritish majburiy",
      profilePictureRequired: "Rasmni yuklash zarur",
      saveTeacherSuccess: "O'qituvchi muvaffaqiyatli saqlandi",
      saveTeacherError: "O'qituvchini saqlashda xatolik yuz berdi",
      deleteTeacherSuccess: "O'qituvchi muvaffaqiyatli o'chirildi",
      deleteTeacherError: "O'qituvchini o'chirishda xatolik yuz berdi",
      noTeachers: "O'qituvchilar topilmadi",
      paginationTeachersTotal: "{range0}-{range1} / {total} O'qituvchilar",
    },
  },
  ru: {
    translation: {
      // Existing translations...
      dashboard: "Панель управления",
      branches: "Филиалы",
      courses: "Курсы",
      gallery: "Галерея",
      login: "Войти",
      logout: "Выйти",
      username: "Имя пользователя",
      password: "Пароль",
      loginButton: "Войти",
      loginTitle: "Вход в админ панель",
      loginSubtitle: "Введите свои данные для доступа к админ панели",
      teachers: "Преподаватели",
      branchesTitle: "Филиалы",
      coursesTitle: "Курсы",
      galleryTitle: "Галерея",
      teachersTitle: "Преподаватели",
      welcome: "Добро пожаловать в панель администратора",
      totalBranches: "Всего филиалов",
      totalCourses: "Всего курсов",
      totalTeachers: "Всего преподавателей",
      vsLastMonth: "по сравнению с прошлым месяцем",
      performanceOverview: "Обзор производительности",
      courseCompletion: "Завершение курса",
      studentSatisfaction: "Удовлетворенность студентов",
      recentActivity: "Недавняя активность",
      quickActions: "Быстрые действия",
      addCourse: "Добавить курс",
      addTeacher: "Добавить преподавателя",
      addBranch: "Добавить филиал",
      addImage: "Добавить изображение",
      by: "от",
      activity: {
        new_course_added: "Добавлен новый курс",
        teacher_profile_updated: "Профиль преподавателя обновлен",
        gallery_image_uploaded: "Изображение в галерее загружено",
        branch_information_modified: "Информация о филиале изменена",
      },
      branchName: "Название филиала",
      branchPhone: "Номер телефона",
      branchAddress: "Адрес",
      edit: "Редактировать",
      delete: "Удалить",
      save: "Сохранить",
      cancel: "Отмена",
      uploadImage: "Загрузить изображение",
      actions: "Действия",
      filterByType: "Фильтровать по типу",
      type1: "Тип 1",
      type2: "Тип 2",
      courseName: "Название курса",
      courseType: "Тип курса",
      coursePrice: "Цена",
      courseDuration: "Продолжительность",
      courseDescription: "Описание",
      branchDescription: "Описание филиала",
      courseDetails: "Детали курса",
      createdDate: "Дата создания",
      uploadImageHint: "Поддержка загрузки одного изображения. Рекомендуемый размер: 800x600px",
      gridView: "Сетка",
      tableView: "Таблица",
      imagePreview: "Предпросмотр изображения",
      noGalleryItems: "Элементы галереи не найдены",
      teacherName: "Имя преподавателя",
      teacherPhone: "Номер телефона",
      teacherExperience: "Опыт",
      graduatedStudents: "Выпускники",
      ieltsScore: "Балл IELTS",
      years: "лет",
      fetchError: "Не удалось загрузить данные",
      profile: "Профиль",
      logout: "Выйти",
      language: "Язык",
      english: "Английский",
      uzbek: "Узбекский",
      russian: "Русский",
      noData: "Нет информации",
      totalStudents: "Всего студентов",
      courseApplications: "Все запросы",
      branchHeader: "Филиалы",
      branchSubtitle: "Управление всеми филиалами",
      addBranchButton: "Добавить филиал",
      editBranch: "Редактировать филиал",
      deleteBranch: "Удалить филиал",
      deleteConfirm: "Вы уверены, что хотите удалить этот филиал?",
      okText: "Да",
      cancelText: "Нет",
      branchNameUz: "Название филиала (Узбекский)",
      branchNameEn: "Название филиала (Английский)",
      branchNameRu: "Название филиала (Русский)",
      contactLabel: "Номер телефона",
      googleUrl: "Google Maps URL",
      yandexUrl: "Yandex Maps URL",
      uploadImageLabel: "Загрузить изображение",
      removeImage: "Удалить изображение",
      existingImageUrl: "URL существующего изображения",
      nameUzRequired: "Название филиала (Узбекский) обязательно",
      nameEnRequired: "Название филиала (Английский) обязательно",
      nameRuRequired: "Название филиала (Русский) обязательно",
      contactRequired: "Номер телефона обязателен",
      googleUrlRequired: "Google Maps URL обязателен",
      yandexUrlRequired: "Yandex Maps URL обязателен",
      imageRequired: "Необходимо загрузить изображение",
      imageSizeError: "Размер изображения должен быть меньше 5 МБ",
      imageTypeError: "Разрешены только файлы изображений",
      uploadSuccess: "Изображение успешно загружено",
      uploadError: "Не удалось загрузить изображение",
      saveSuccess: "Филиал успешно сохранен",
      saveError: "Не удалось сохранить филиал",
      deleteSuccess: "Филиал успешно удален",
      deleteError: "Не удалось удалить филиал",
      noBranches: "Филиалы не найдены",
      paginationTotal: "{range0}-{range1} из {total} филиалов",
      studentsHeader: "Студенты",
      addStudentButton: "Добавить студента",
      editStudent: "Редактировать студента",
      deleteStudent: "Удалить студента",
      deleteStudentConfirm: "Вы уверены, что хотите удалить этого студента?",
      totalStudentsLabel: "Всего студентов",
      studentName: "Студент",
      cefrLevel: "Уровень CEFR",
      certificate: "Сертификат",
      viewCertificate: "Просмотреть",
      noCertificate: "Недоступно",
      nameUzLabel: "Имя (Узбекский)",
      nameEnLabel: "Имя (Английский)",
      nameRuLabel: "Имя (Русский)",
      cefrLevelLabel: "Уровень CEFR",
      ieltsScoreLabel: "Балл IELTS",
      certificateUploadLabel: "Загрузить изображение сертификата",
      nameUzRequired: "Имя (Узбекский) обязательно",
      nameEnRequired: "Имя (Английский) обязательно",
      nameRuRequired: "Имя (Русский) обязательно",
      cefrLevelRequired: "Уровень CEFR обязателен",
      ieltsScoreRequired: "Балл IELTS обязателен",
      certificateRequired: "Необходимо загрузить изображение сертификата",
      certificateUrlLabel: "URL существующего сертификата",
      saveStudentSuccess: "Студент успешно сохранен",
      saveStudentError: "Не удалось сохранить студента",
      deleteStudentSuccess: "Студент успешно удален",
      deleteStudentError: "Не удалось удалить студента",
      noStudents: "Студенты не найдены",
      // New translations for Teachers component
      teachersHeader: "Преподаватели",
      teachersSubtitle: "Управление всеми преподавателями",
      addTeacherButton: "Добавить преподавателя",
      editTeacher: "Редактировать преподавателя",
      deleteTeacher: "Удалить преподавателя",
      deleteTeacherConfirm: "Вы уверены, что хотите удалить этого преподавателя?",
      teacherNameLabel: "Преподаватель",
      experienceYears: "Опыт",
      graduatedStudentsLabel: "Выпускники",
      contactLabel: "Номер телефона",
      profilePictureLabel: "Загрузить фото профиля",
      profilePictureUrlLabel: "URL существующего фото профиля",
      nameUzRequired: "Имя (Узбекский) обязательно",
      nameEnRequired: "Имя (Английский) обязательно",
      nameRuRequired: "Имя (Русский) обязательно",
      contactRequired: "Номер телефона обязателен",
      experienceYearsRequired: "Опыт обязателен",
      graduatedStudentsRequired: "Количество выпускников обязательно",
      ieltsScoreRequired: "Балл IELTS обязателен",
      profilePictureRequired: "Необходимо загрузить фото профиля",
      saveTeacherSuccess: "Преподаватель успешно сохранен",
      saveTeacherError: "Не удалось сохранить преподавателя",
      deleteTeacherSuccess: "Преподаватель успешно удален",
      deleteTeacherError: "Не удалось удалить преподавателя",
      noTeachers: "Преподаватели не найдены",
      paginationTeachersTotal: "{range0}-{range1} из {total} преподавателей",
    },
  },
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "en",
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ["localStorage", "navigator", "htmlTag"],
      caches: ["localStorage"],
    },
  });

export default i18n;